# Generated by Django 6.0.3 on 2026-04-19 20:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('interview_type', models.CharField(max_length=20)),
                ('difficulty', models.CharField(max_length=10)),
                ('question_text', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('hint', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('Frontend Developer', 'Frontend Developer'), ('Backend Developer', 'Backend Developer'), ('Full Stack', 'Full Stack'), ('Data Analyst', 'Data Analyst'), ('Product Manager', 'Product Manager'), ('UX Designer', 'UX Designer'), ('ML Engineer', 'ML Engineer'), ('DevOps Engineer', 'DevOps Engineer')], max_length=50)),
                ('interview_type', models.CharField(choices=[('Technical', 'Technical'), ('Behavioural', 'Behavioural'), ('HR Round', 'HR Round'), ('Mixed', 'Mixed')], default='Technical', max_length=20)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=10)),
                ('question_count', models.IntegerField(default=8)),
                ('time_per_question', models.CharField(default='5min', max_length=20)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('communication_score', models.FloatField(blank=True, null=True)),
                ('technical_score', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('ai_feedback', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('question_text', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('hint', models.TextField(blank=True, default='')),
                ('user_answer', models.TextField(blank=True, default='')),
                ('is_answered', models.BooleanField(default=False)),
                ('is_skipped', models.BooleanField(default=False)),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('communication_score', models.FloatField(blank=True, null=True)),
                ('technical_score', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('ai_feedback', models.TextField(blank=True, default='')),
                ('clarity_score', models.FloatField(blank=True, null=True)),
                ('examples_score', models.FloatField(blank=True, null=True)),
                ('depth_score', models.FloatField(blank=True, null=True)),
                ('length_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='crackAI.interviewsession')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SessionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_label', models.CharField(default='', max_length=50)),
                ('grade_title', models.CharField(default='', max_length=100)),
                ('grade_message', models.TextField(default='')),
                ('communication_score', models.FloatField(default=0)),
                ('technical_score', models.FloatField(default=0)),
                ('confidence_score', models.FloatField(default=0)),
                ('examples_score', models.FloatField(default=0)),
                ('structure_score', models.FloatField(default=0)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('ai_feedback', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='crackAI.interviewsession')),
            ],
        ),
        migrations.CreateModel(
            name='ImprovementPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='💡', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tag_label', models.CharField(default='HIGH IMPACT', max_length=50)),
                ('tag_color', models.CharField(default='coral', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvements', to='crackAI.sessionresult')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
