# Generated by Django 6.0.3 on 2026-04-19 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Frontend Engineer @ Startup — 6-Month Blueprint', max_length=200)),
                ('target_role', models.CharField(help_text='e.g. Frontend Engineer at a Startup', max_length=200)),
                ('timeline_months', models.IntegerField(choices=[(3, '3 Months'), (6, '6 Months'), (12, '12 Months')], default=6)),
                ('interests', models.JSONField(default=list, help_text='List of selected interest areas')),
                ('additional_ctx', models.TextField(blank=True, help_text='Extra context the user provided')),
                ('total_weeks', models.IntegerField(default=24)),
                ('completed_weeks', models.IntegerField(default=0)),
                ('current_week', models.IntegerField(default=1)),
                ('progress_pct', models.FloatField(default=0.0, help_text='0 to 100')),
                ('ai_summary', models.TextField(blank=True, help_text="Gemini's overall summary message")),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('draft', 'Draft')], default='active', max_length=20)),
                ('version', models.IntegerField(default=1, help_text='Increments each time roadmap is regenerated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='💡', help_text='Emoji icon for the card', max_length=10)),
                ('title', models.CharField(help_text='e.g. Pace Recommendation', max_length=100)),
                ('body', models.TextField(help_text='The insight text shown in the card')),
                ('order', models.IntegerField(default=0)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='campuspathAI.roadmap')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(help_text='Start week number, e.g. 1')),
                ('week_end', models.IntegerField(help_text='End week number, e.g. 4 (same as week_number if single week)')),
                ('title', models.CharField(help_text='e.g. HTML, CSS & JavaScript Deep Dive', max_length=200)),
                ('description', models.TextField(help_text='What the student will learn this week')),
                ('mini_project', models.CharField(blank=True, help_text='e.g. Personal Portfolio Site', max_length=300)),
                ('key_skills', models.CharField(blank=True, help_text='e.g. HTML5, CSS Grid, ES6+', max_length=300)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Display order in the timeline')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='campuspathAI.roadmap')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SkillGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('have', 'Have'), ('partial', 'Partial'), ('missing', 'Missing')], max_length=10)),
                ('level', models.CharField(choices=[('Expert', 'Expert'), ('Proficient', 'Proficient'), ('Developing', 'Developing'), ('Learning', 'Learning'), ('Beginner', 'Beginner'), ('In progress', 'In progress'), ('Basic', 'Basic'), ('Missing', 'Missing')], default='Missing', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gaps', to='campuspathAI.roadmap')),
            ],
            options={
                'ordering': ['status', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SkillGapPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_text', models.TextField(help_text="Gemini's priority order recommendation")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roadmap', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gap_priority', to='campuspathAI.roadmap')),
            ],
        ),
        migrations.CreateModel(
            name='SkillProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(help_text='e.g. React / Frontend', max_length=100)),
                ('percentage', models.IntegerField(default=0, help_text='0–100')),
                ('color_start', models.CharField(default='var(--sky)', help_text='CSS gradient start color', max_length=30)),
                ('color_end', models.CharField(default='#8b5cf6', help_text='CSS gradient end color', max_length=30)),
                ('order', models.IntegerField(default=0)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_progress', to='campuspathAI.roadmap')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_url', models.URLField(blank=True, help_text='e.g. https://github.com/username', null=True)),
                ('github_username', models.CharField(blank=True, max_length=100)),
                ('github_connected', models.BooleanField(default=False)),
                ('github_repos', models.IntegerField(default=0, help_text='Number of public repos')),
                ('github_contribs', models.IntegerField(default=0, help_text='Total GitHub contributions')),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='campuspath_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(help_text='e.g. React, TypeScript', max_length=100)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('learning', 'Learning'), ('developing', 'Developing'), ('proficient', 'Proficient'), ('expert', 'Expert')], default='proficient', max_length=20)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='campuspathAI.roadmap')),
            ],
        ),
        migrations.CreateModel(
            name='WeekResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. MDN Web Docs', max_length=100)),
                ('url', models.URLField(blank=True, help_text='Direct link to resource')),
                ('emoji', models.CharField(default='📖', help_text='Emoji icon for the resource', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='campuspathAI.roadmapweek')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WeekTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Task description shown as checkbox label', max_length=300)),
                ('is_done', models.BooleanField(default=False)),
                ('est_hours', models.CharField(blank=True, help_text="e.g. '4–6 hrs'", max_length=30)),
                ('task_type', models.CharField(default='Core', help_text='e.g. Core, Polish, CI/CD', max_length=30)),
                ('order', models.IntegerField(default=0)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='campuspathAI.roadmapweek')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
