# Generated by Django 6.0.3 on 2026-09-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuspathAI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillprogress',
            name='percentage',
        ),
        migrations.AddField(
            model_name='skillprogress',
            name='target_percentage',
            field=models.IntegerField(default=0, help_text="Gemini's estimate once roadmap is fully completed"),
        ),
    ]
