# Generated by Django 6.0.3 on 2026-04-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.CharField(max_length=5)),
                ('message', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
