# Generated by Django 6.0.2 on 2026-04-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='message',
        ),
        migrations.AddField(
            model_name='review',
            name='description',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='course',
            field=models.CharField(max_length=15),
        ),
    ]
