# Generated by Django 6.0.2 on 2026-04-14 10:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupIdea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idea_text', models.TextField()),
                ('idea_name', models.CharField(blank=True, max_length=200)),
                ('industry', models.CharField(choices=[('edtech', 'EdTech'), ('fintech', 'FinTech'), ('healthtech', 'HealthTech'), ('saas', 'SaaS / B2B'), ('e-commerce', 'E-Commerce'), ('devtools', 'Developer Tools'), ('climate-tech', 'Climate Tech'), ('deep-tech', 'Deep Tech / AI')], max_length=20)),
                ('market', models.CharField(choices=[('students', 'Students / College'), ('businesses', 'Small Businesses'), ('enterprise', 'Enterprise'), ('consumers', 'Consumers (B2C)'), ('devs', 'Developers'), ('healthcare', 'Healthcare Providers'), ('government', 'Government / Public Sector')], max_length=20)),
                ('stage', models.CharField(choices=[('idea', 'Idea Stage'), ('mvp', 'Prototype / MVP'), ('revenue', 'Early Revenue'), ('growth', 'Growth Stage')], max_length=20)),
                ('ai_edge_insight', models.TextField(blank=True)),
                ('is_saved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('tam', models.CharField(max_length=100)),
                ('sam', models.CharField(max_length=100)),
                ('som', models.CharField(max_length=100)),
                ('cagr', models.CharField(max_length=50)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_size', to='ventureIQ.startupidea')),
            ],
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('threat_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='ventureIQ.startupidea')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BusinessBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_solution', models.TextField()),
                ('problem_highlight', models.CharField(blank=True, max_length=200)),
                ('business_model', models.TextField()),
                ('business_highlight', models.CharField(blank=True, max_length=200)),
                ('gtm_strategy', models.TextField()),
                ('gtm_highlight', models.CharField(blank=True, max_length=200)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brief', to='ventureIQ.startupidea')),
            ],
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('advantage', 'Biggest Advantage'), ('risk', 'Biggest Risk'), ('monetization', 'Monetization Path')], max_length=20)),
                ('content', models.TextField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='ventureIQ.startupidea')),
            ],
        ),
        migrations.CreateModel(
            name='SWOTAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('opportunities', models.JSONField(default=list)),
                ('threats', models.JSONField(default=list)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='swot', to='ventureIQ.startupidea')),
            ],
        ),
        migrations.CreateModel(
            name='ViabilityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('verdict', models.CharField(choices=[('strong', 'Strong Market Potential'), ('moderate', 'Moderate Market Potential'), ('weak', 'Weak Market Potential'), ('risky', 'High Risk — Proceed Carefully')], max_length=10)),
                ('market_pct', models.IntegerField()),
                ('competitive_pct', models.IntegerField()),
                ('scalability_pct', models.IntegerField()),
                ('revenue_pct', models.IntegerField()),
                ('geography', models.CharField(max_length=100)),
                ('business_type', models.CharField(max_length=50)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='viability', to='ventureIQ.startupidea')),
            ],
        ),
    ]
